sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: a1fFwOwUdXXdDoJK1hJFzfyFonVPvsv1BjryfEgOvvZt9HNd3mgne/av3n132IKYmIzxS/1i5kwc52aR95CLIMe7G31bQ2Iqpx0et70iSSp6TXOBIAVW3nStJKLqx522dmnePhrfC39PWg5OyN1oyVG8qrBEU0SkRUfNM0cBt7N6Eke45LAmuQTE0UFiV0+VxkUjVq68HaUiTL7AmzxoR9XUvHDDG5Fv5Ocl1N3nMEDmVQMCW4dTR8n9LRWbEahQo6b70Qbeykc5rjoONrNi3sKG+5pp/OBpvuq6NS7qipQT28kReTIHLDP5XtHmjShS/G18Q7WaFbXa/O93kt2mYk9etzzvBpOw2FT3yTR+t6gLehxnym881YyRrX+kGeOcfZ4sA4bucTb5balTq6O3m6KgIDkw85+r6sRl7RRZQKGHbB9ya77NgpwwZoA2lA3NC1WIW0la5e0B6vwXskNbWGF9P0QxAU34wh76GeGKNuiBHJYN/eNyeOkqBhLAPrluUniJ0qIkuh46Kit/+eGWO8MFpB0BYvxmTJ5LABXrQdOFyTmy9jPmdD4+6cP3aIX4nno1oTWnuccYxScAyNknYW8i2hhRIoyNVz4DVrOsYEshbsGh39sJTgMGmq5G84if9fbtMpUC3nMVMMYW+oGMfy96Gsj9lGHHdRgwE1P/ID8=
    secure: VYoxK9bnd9try3rcl0L4i9mb/fdvkNXhl8I0E4+JKoBCNhevH2X+DKgDZoppN7M9r9PvxT7UZXDkZM1QtahpEfGhT94ednkmKGb+EZWI6k3R9NBxAU1C69+CIxWyCykx/cOe9HRQwdzrSLkYxF8j5e/ORTwnDoCEslKWhq1CPjFC+gvP5Q5xLdMMB12pARMKAcKJMelR42Ggt986aFqajqqle8z7vK/kOLc/bauZh07MuzbI+v2FnFmP6dYZVuKnVe4b0xlE965yzPWJMYcjYDQpKhOIvsOzoO14wD7Gkx95RodZNusek7AyRmTBvo9TUhG5S8OP1KmUr+XevigKjQxnnerDjHwrGB+DH2cQ1qS/xOgRwOC1EmFT8PGnBWRZYSlslL5eH/xQJWtVQtURJtmZcf4jnsM8T1e7C7zKxt9xTrFzs0iCz+lhqO9IObvqowAxii4X16/zKmxv2frhlxW1DRQQdB8IVZJ1sjVBQ3eSLqj6M0jtzOOKjhzb/+zStUOLdKEB9THBRqe2IsOQUuQy4jkxygcmpCLwe4IfddRqrBbiomghPbzpeEzldMmQ9FtiyS2T8KwtFlU5YtO/3ERO6RbK+gV2MihncxakvyDTVvlBwj26DYu1GQcGat8UsQ88P+BDZMtqgXBnD9wrhh09ThSnHu0ATTkdcUcPLBU=
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d; fi
