sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: hg0QxvdrYQgDkTKXVW6aQWZFUcuCkcx84h/qYS/Krw0uNlryQjOwKfWr6ZJIVM/Kav1Wx3KFXy7ELe4bCRwHJqoCMYa+EH/0AU/BAqHBkfuO50VyjlW0qOWNMcslYWovnJU0fDtM5QKfKUx8yEXVekEIOTcPRpH669HYkSfM8hSelfftJPEfjH9UP2YFv8aOMMJRX/M+5Sj89kKShia4wYs6D/BPTPjWj1zLTBaOCKdg4tkOF86VxFiSvPCMwcTuNOhQ3kA8jxvWawXeMNvCNmxTRqBgEyK6DlcTZMU65F5xySLh38hsQrADeb9BA8fPN421eQY/C/gFp94hG1H4mXTrDQnx9Wn+1QUEjHrfAXdHYJF4J7wm3Iubn/7VkfW0nZxdzSWiq3RwjT3mYC6/rEB5RoBFFsOwWAWh05aA5rPPauqRfleeIFgOjMmilfl4GNF5lq/YMxy7brKRC62vdYLfuWKJlkIQd+DTR4OivKlW6WzRabALIwJrUj5FaAmFqmmF9GECc6jz+iwcIeyY+2va9A/pAXLTkB0+ifpgOvJLhEl19+k0qHfG2FUNEWLSbfc/EZGNi5E0YjdqF3o0/pzyrayoSf6JpavqBYYbFeI8oWcJNzI3qPvaFhwayBzc2nx6ydGpwfEMejao2jlFwPkwIfBbG2+GqaxkY0kWORw=
  - secure: ByGTg655yUN63RouuYYFZ6WU+pFSqLFrBSLXofFiSkirOB55QOmj+mVcfsYU4d+0P1v4u+OeYgxhXVuFMF6hyMd2KacSncXSg7gDCzepG+yMTgtm7ku6MAvwOMHCeNPgxQeSfh+d3W9Na/mSJaF3EktEB9jugPwqBiSfOYaN9watMSiKw2Mn3fk+/TpnfPh9K97HXACMpZnNO8Co38hB/bAO8Dlt2+DuuDvXdQyTajnWsN90vMa8ZDlk+AC0pJBFhi/nML1v+smgFcUhteMHXsFNuzqV0sqzRTJbxyb92YnooxhulKhAF2NPdRMPrJAR00vgB2mAi5ymaFLlQakc5R6Et59eX2rXGZAQCBANxlSMH6uF3TUFFwJld2dZ+JIJyae0jsPXAr/akThmVM6CGR29ewY3As5RGksgkNBY3nEwifEXqFvvD395321KgO16j3DOlSRMBasvZcd4SFAVS+U7QNTxav4TKcz+YaG/9BGc27YcEWLXgR9Nl1kmDySqr0FNK+8Oo0MO+M2JJSZ9vJulXLGPcMzy3hiAle8YOEp3Ncwu4RFUx4thlkm6Hks82A3akGneaTsDpHXK9E+6x9I4x4C7XyvKibYkMKJHP1c3gTrUObDZ0P+w+9c1i4AJICP6uAVjKBFA+wmAAEVNFkkT/SpGoHecxW2Qha7YEUs=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
