sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: VUDXalwfw19DViVbCGe3tsKmKoKpTjhk7TlvVF3bysriiDupM1+ppp5rMx5mi0w4w+OKrobSuNbstx8gUc8XQoz9EqhgQNxyIgDbtrg6hkjVY+GN6+GmXChtdWGKBXxGxnexBgmmI83C3jLwM9fGAak1iGMxG88PVBA2IvvKWdRGS4QIGFHUPTGK9KmjlInJznwYD5LfdZ1T8tHbLW2vCBbZn5JP7AqXpNMyQFoU6YOJ9o0wsQiiJ+QoyXZ+6+hhGP5/HL9ob2gy5VrAs387WnFgrFgx8T7zPz0s3Kp4THSozds0KmuSo3MA7yccZ/kVj0aaK/xkkyjUXBPrQmNcZpe7miVip3fVHrRdnZje4HCj+L7n8K8HdGQst0o21VerEiCO7nVKk6C5n1TuTWoh86WAMDG5vyAvFj+FKAN4+RAQrbnLmopXNUpWzCFuDGPkZFtKT7rgnKBVjPmQ/+d2eK9WGZi1m8CXYMBMuJBwbw5LBv1srQrmqE7dpzHILyYXe2ogZxmWrkM2VYNapDc6oPy6f2P1p1oA0v1BqJDDl8w+x4pdgyzieCCMAu469oEt/u18Uj+fjk9B9AAo5ILW9YhnOtzUm6N96L2qw29Giq1llXvS12Yf62/UQ/4bK1aEbLxJu/Y7j/xchSFdVGB4Cd+nF3GeQ8BdPgCT96W1qXc=
  - secure: iMy/0QmswK9VgWs6hWcA+blkdH54GLXIODqxvaWSoq+qKOmE54YH8W0KkDXkYAs6LJppQhAHCq8FRPSxa2w7XTRwYTQ3DLJ7bePKncHNJhfwqBGDNx/QSmYKOk4lvCdL33qnwBuOYYJZ0v6YIG/FhctsmRYKEUI9A7r5LIcFZ4g1wj9Q5V3q72WfVUywnb71cS7TOUrhJ9k/FSAwwDWbnbeLe9PGWSKtvC1HyQc5/1s6c/61ueFWAZC287b44dI6roggdnIKzJmf6gaz+Ty60WzETJbi214uoq+dWUsCXeYJo9cU4AdJxIbG66hHZROfoUfI7JAWO6pkw3sU/wiPWou7NN369b5Xj4wHoxTr1DNpBB3WKV3/v/4/mZjsHcAAwu9RUOdzL/0KzAei8ZZhsf4zeecIIvHx4XbhGhHZrDRbFDGrE7zcwNWV3Z/tewaV4RRkPd4yTzOYO87b8/IpzXhB1K5CX+OZNzKhLRvyvRJa5lwxztsIcXuKwZ+K6axQbGSa+0ls4XE1/MOLmnymeUeQQidAZaoIgIl59gRda1gvTxOXpeX+YqvHeWCDziHPAeKUuxG60xJxSblLjpuZyDGZ/1sEm1eTpIlzPZt5oqOBOts8TNHwGNODPfHqCGGAV9lpJLo0zD/0a1QYqfHhRjquqzANH6xcEkKihpipjEk=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
